version: "3.8"

services:
  mysql:
    image: mysql:latest
    restart: always
    container_name: mysql_delivery
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3306:3306
    volumes:
      - ./databases:/backup